name: "Hello Actions"
description: "Greet someone"
author: "libialany@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "mic"
  color: "purple"

  
